--------------------------------------------------------------------------------
---------------------------------- DokusCore -----------------------------------
--------------------------------------------------------------------------------
-- Just for testing quick things. Can be ignored!
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- RegisterCommand('note', function()
--   -- TriggerEvent('DokusCore:Notify:Toast', 'alert', 'Dokus ADS', 'This is some random DOkus ADD' )
--   -- TriggerEvent('MyNotify:Left', 'Title', 'sold', 'menu_textures', 'menu_icon_alert',  10000)
--   NoteObjective('Gold Title', 'Text Message', 'InView', 5000) Wait(7000)
--   NoteObjective('Valentine Law', 'Deputy DevDokus', 'OutView', 5000) Wait(7000)
--   NoteObjective('Valentine Law', 'Deputy DevDokus', 'Kick', 5000) Wait(7000)
--   NoteObjective('Valentine Law', 'Deputy DevDokus', 'Health', 5000) Wait(7000)
--   NoteObjective('Valentine Law', 'Deputy DevDokus', 'Shield', 5000) Wait(7000)
--   NoteObjective('Valentine Law', 'Deputy DevDokus', 'Warning', 5000) Wait(7000)
-- end)

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
