--------------------------------------------------------------------------------
---------------------------------- DokusCore -----------------------------------
--------------------------------------------------------------------------------
----------------------- I feel a disturbance in the force ----------------------
--------------------------------------------------------------------------------
-- RegisterNUICallback('set_job', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--
-- RegisterNUICallback('edit_money', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--
-- RegisterNUICallback('edit_gold', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--
-- RegisterNUICallback('edit_staff_perms', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- RegisterNUICallback('heal', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--
-- RegisterNUICallback('spectate', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--     TriggerServerEvent('rdrp_admin:spectate', source, data, Config.Perms.Spectate )
-- end)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- RegisterNUICallback('chain', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--
-- RegisterNUICallback('slap', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--     TriggerServerEvent('rdrp_admin:slap', source, data, Config.Perms.Slap )
-- end)
--
-- RegisterNUICallback('slay', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--     TriggerServerEvent('rdrp_admin:slay', source, data, Config.Perms.Slay )
-- end)
--
-- RegisterNUICallback('kick', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--
-- RegisterNUICallback('ban', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--
-- end)
--
--
-- -- Net events for NUI callbacks
--
-- -- Warn player
-- RegisterNetEvent('rdrp_admin:warn', function(data)
--     print("YOU HAVE BEEN WARNED")
--     print("--------------------------------")
--     print(data)
-- end)
--
-- -- Slap player
-- RegisterNetEvent('rdrp_admin:slap', function()
--     local ped = GetPlayerPed(PlayerId())
--     ApplyDamageToPed(ped, 10, false, true, true)
-- end)
--
-- -- Slay player
-- RegisterNetEvent('rdrp_admin:slay', function()
--     local ped = GetPlayerPed(PlayerId())
--     ApplyDamageToPed(ped, 500000, false, true, true)
-- end)
--
--
-- RegisterNetEvent('rdrp_admin:slay', function()
--
-- end)
--
--
-- RegisterNetEvent('rdrp_admin:slay', function()
--
-- end)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- RegisterNUICallback('goto', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--     TriggerServerEvent('rdrp_admin:goto', source, data, Config.Perms.Goto )
-- end)
--
-- RegisterNUICallback('bring', function(data, cb)
--     data.staff = GetPlayerName(PlayerId())
--     TriggerServerEvent('rdrp_admin:bring', source, data, Config.Perms.Bring )
-- end)
--
--
-- -- Net events for NUI callbacks
--
-- -- Bring player
-- RegisterNetEvent('rdrp_admin:bring', function()
--
-- end)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
